name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: .node-version

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Checks
        run: yarn check
